import English from './English'
import Images from './Images'

const Constants = {
  AuthContainerArray: [
    {
      name: 'email',
      labelText: English.E3,
      placeHolderText: English.E4,
      type: 'text',
    },
    {
      name: 'password',
      labelText: English.E5,
      placeHolderText: English.E6,
      type: 'password',
    },
  ],
  SidebarData: [
    {
      icon: Images.dashboard,
      title: English.E21,
      linkTo: '/dashboard',
    },
    {
      icon: Images.certificates,
      title: English.E22,
      linkTo: '/certificates',
    },
    {
      icon: Images.certificates,
      title: English.E23,
      linkTo: '/payout',
    },
    {
      icon: Images.certificates,
      title: English.E24,
      linkTo: '/billing',
    },
    {
      icon: Images.certificates,
      title: English.E25,
      linkTo: '/profile',
    },
    {
      icon: Images.home,
      title: English.E30,
      linkTo: '/',
    },
  ],
  ChallengeOptions: [
    {title: English.E32, content: English.E33},
    {title: English.E34, content: English.E35},
  ],
  ChallengeStaticTableContent: {
    tableHeadings: ['', English.E36, English.E37, English.E38],
    tableBodyData: [
      {
        checked: false,
        checkBoxRole: 'initiator',
        role: 'Initiator',
        price: '$69',
        amount: '$5,000 USDT',
      },
      {
        checked: false,
        checkBoxRole: 'challengerRole',
        role: 'Challenger',
        price: '$99',
        amount: '$10,000 USDT',
      },
      {
        checked: false,
        checkBoxRole: 'strategistRole',
        role: 'Strategist',
        price: '$249',
        amount: '$25,000 USDT',
      },
      {
        checked: false,
        checkBoxRole: 'expertRole',
        role: 'Expert',
        price: '$399',
        amount: '$50,000 USDT',
      },
      {
        checked: false,
        checkBoxRole: 'championRole',
        role: 'Champion',
        price: '$699',
        amount: '$100,000 USDT',
      },
      {
        checked: false,
        checkBoxRole: 'grandmasterRole',
        role: 'Grandmaster',
        price: '$999',
        amount: '$200,000 USDT',
      },
    ],
  },
  StatsData: [
    {
      mainHeading: 'Stage 1',
      subHeading: '',
      content: ['Demo evaluation passed.'],
      isUnlock: true,
      isActive: false,
    },
    {
      mainHeading: 'Stage 2',
      subHeading: 'Verification Stage',
      content: [
        'Prove consistency with relaxed profit targets to move to funded.',
      ],
      isUnlock: true,
      isActive: true,
    },
    {
      mainHeading: 'Stage 3',
      subHeading: '',
      content: ['Live funded account unlocked after passing Stage 2.'],
      isUnlock: true,
      isActive: false,
    },
  ],
  CustomTradingStats: {
    Trading_Stats: [
      {
        title: English.E61,
        first_content: '3000',
        second_content: '3120',
        type: 'lablelType',
        subType: '',
        isProgressBarType: false,
      },
      {
        title: English.E62,
        first_content: '---',
        second_content: '---',
        subType: '',
        type: 'lablelType',
        isProgressBarType: false,
      },
      {
        title: English.E63,
        first_content: '5995.23',
        subType: '',
        type: 'normalType',
        isProgressBarType: false,
      },
    ],
    [English.E64]: [
      {
        title: English.E66,
        first_content: '5',
        second_content: '0',
        type: 'winProgressType',
        subType: 'days',
        isProgressBarType: true,
      },
      {
        title: English.E68,
        first_content: '500',
        second_content: '0',
        type: 'winProgressType',
        subType: 'money',
        isProgressBarType: true,
      },
      {
        title: English.E69,
        first_content: '500',
        second_content: '0',
        type: 'lossProgressType',
        subType: 'money',
        isProgressBarType: true,
      },
      {
        title: English.E70,
        first_content: '1000',
        second_content: '0',
        type: 'lossProgressType',
        subType: 'loss_money',
        isProgressBarType: true,
      },
    ],
    [English.E71]: [
      {
        title: English.E72,
        first_content: '0',
        type: 'longShortType',
        subType: '',
        isProgressBarType: false,
      },
      {
        title: English.E78,
        first_content: '0',
        type: 'winLossType',
        subType: '',
        isProgressBarType: false,
      },
      {
        title: English.E78,
        first_content: '0',
        type: 'normalMoneyType',
        subType: 'win_rate',
        isProgressBarType: false,
      },
      {
        title: English.E79,
        first_content: '0',
        type: 'normalMoneyType',
        subType: 'win_rate',
        isProgressBarType: false,
      },
    ],
  },
  ClosedPNL: [
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.5,
      entryValue: '12,500 USDT',
      exitValue: '12,750 USDT',
      entryPrice: '25,000',
      exitPrice: '25,500',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.51,
      entryValue: '15,000 USDT',
      exitValue: '12,750 USDT',
      entryPrice: '12,902',
      exitPrice: '25,200',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.23,
      entryValue: '9,500 USDT',
      exitValue: '189 USDT',
      entryPrice: '25,000',
      exitPrice: '25,500',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.19,
      entryValue: '1,500 USDT',
      exitValue: '12 USDT',
      entryPrice: '43,199',
      exitPrice: '43,199',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
  ],
  CertificateTabHeading: [
    {title: English.E91, img: ''},
    {title: English.E92, img: ''},
    {title: English.E93, img: ''},
  ],
  Certificate: {
    CertificatesBodyData: [
      {
        certificateId: 'CT-2025-001',
        challengeName: 'Two-Step Challenge',
        tradingCapital: '1000',
        status: '✅ Passed',
        issueDate: '2025-09-10',
        action: 'Download',
      },
      {
        certificateId: 'CT-2025-002',
        challengeName: 'One-Step Challenge',
        tradingCapital: '25000',
        status: '🎯 Profit Target',
        issueDate: '2025-08-28',
        action: 'Download',
      },
      {
        certificateId: 'CT-2025-003',
        challengeName: 'Free Trial',
        tradingCapital: '5000',
        status: '✅ Passed',
        issueDate: '2025-07-15',
        action: 'Download',
      },
    ],
    CertificatesHeadingData: [
      English.E94,
      English.E95,
      English.E96,
      English.E52,
      English.E98,
      English.E99,
    ],
  },
  Payout: {
    PayoutTableBodyData: [
      {
        payoutId: 'P-2025-001',
        date: '2025-09-05',
        amount: '10000',
        status: '✅ Paid',
        method: 'USDT (Wallet)',
        transactionId: '0x93f...a82c',
      },
      {
        payoutId: 'P-2025-002',
        date: '2025-08-20',
        amount: '25000',
        status: '✅ Paid',
        method: 'USDT (Wallet)',
        transactionId: '0x93f...a82c',
      },
    ],
    PayoutTableHeadingData: [
      English.E103,
      English.E104,
      English.E105,
      English.E52,
      English.E107,
      English.E108,
    ],
  },
  Billing: {
    BillingTableBodyData: [
      {
        invoiceId: 'P-2025-001',
        date: '2025-09-05',
        challenge: 'Two-Step',
        plan: 'Initiater',
        amount: '$69',
        status: '✅ Paid',
        transactionId: '0x93f...a82c',
        action: 'Download',
      },
      {
        invoiceId: 'P-2025-002',
        date: '2025-08-20',
        challenge: 'One-Step',
        plan: 'Strategist',
        amount: '$249',
        status: '🚫 Failed',
        transactionId: '0x93f...a82c',
        action: 'Download',
      },
    ],
    BillingTableHeadingData: [
      English.E111,
      English.E104,
      English.E97,
      English.E106,
      English.E105,
      English.E52,
      English.E108,
      English.E99,
    ],
  },
  ChallengesTabContent: [
    {title: English.E114, content: English.E33},
    {title: English.E115, content: English.E35},
    {title: English.E116, content: English.E35},
  ],
  ConstantChallengeData: {
    Status: 'Ongoing',
    'Current balance': '10,000',
    'Minimum Trading Days': '5',
    Challenge: 'Two Step',
    'Trading type': 'Futures',
    'Drawdown type': 'Trailing',
    'Challenge type': 'Zeno Challenger',
  },
}

export default Constants
