import English from './English'
import Images from './Images'

const Constants = {
  AuthContainerArray: [
    {
      name: 'email',
      labelText: English.E3,
      placeHolderText: English.E4,
      type: 'text',
    },
    {
      name: 'password',
      labelText: English.E5,
      placeHolderText: English.E6,
      type: 'password',
    },
  ],
  NewPasswordInoutArray: [
    {
      name: 'otp',
      labelText: English.E306,
      placeHolderText: English.E307,
      type: 'text',
    },
    {
      name: 'new_password',
      labelText: English.E311,
      placeHolderText: English.E312,
      type: 'password',
    },
    {
      name: 'confirm_new_password',
      labelText: English.E309,
      placeHolderText: English.E310,
      type: 'password',
    },
  ],

  SidebarData: [
    {
      icon: Images.dashboard,
      title: English.E21,
      linkTo: '/dashboard',
    },
    {
      icon: Images.certificates,
      title: English.E22,
      linkTo: '/certificates',
    },
    {
      icon: Images.certificates,
      title: English.E23,
      linkTo: '/payout',
    },
    {
      icon: Images.certificates,
      title: English.E24,
      linkTo: '/billing',
    },
    {
      icon: Images.certificates,
      title: English.E25,
      linkTo: '/profile',
    },
    {
      icon: Images.home,
      title: English.E30,
      linkTo: '/',
    },
  ],
  ChallengeStaticTableContent: {
    tableHeadings: [
      {content: [''], showArrow: false},
      {content: [English.E36], showArrow: false},
      {content: [English.E37], showArrow: false},
      {content: [English.E38], showArrow: false},
    ],
    // tableBodyData: [
    //   {
    //     checked: false,
    //     checkBoxRole: 'initiator',
    //     role: 'Initiator',
    //     price: '$69',
    //     amount: '$5,000 USDT',
    //   },
    //   {
    //     checked: false,
    //     checkBoxRole: 'challengerRole',
    //     role: 'Challenger',
    //     price: '$99',
    //     amount: '$10,000 USDT',
    //   },
    //   {
    //     checked: false,
    //     checkBoxRole: 'strategistRole',
    //     role: 'Strategist',
    //     price: '$249',
    //     amount: '$25,000 USDT',
    //   },
    //   {
    //     checked: false,
    //     checkBoxRole: 'expertRole',
    //     role: 'Expert',
    //     price: '$399',
    //     amount: '$50,000 USDT',
    //   },
    //   {
    //     checked: false,
    //     checkBoxRole: 'championRole',
    //     role: 'Champion',
    //     price: '$699',
    //     amount: '$100,000 USDT',
    //   },
    //   {
    //     checked: false,
    //     checkBoxRole: 'grandmasterRole',
    //     role: 'Grandmaster',
    //     price: '$999',
    //     amount: '$200,000 USDT',
    //   },
    // ],
  },

  StatsDataTwoStep: [
    {
      mainHeading: 'Stage',
      subHeading: '',
      content: ['Demo evaluation passed.'],
      isUnlock: true,
      isActive: false,
    },
    {
      mainHeading: 'Stage',
      subHeading: 'Verification Stage',
      content: [
        'Prove consistency with relaxed profit targets to move to funded.',
      ],
      isUnlock: true,
      isActive: true,
    },
    {
      mainHeading: 'Stage',
      subHeading: '',
      content: ['Live funded account unlocked after passing Stage 2.'],
      isUnlock: true,
      isActive: false,
    },
  ],

  StatsDataOneStep: [
    {
      mainHeading: 'Stage 1',
      subHeading: '',
      content: ['Demo evaluation passed.'],
      isUnlock: true,
      isActive: false,
    },
    {
      mainHeading: 'Stage 2',
      subHeading: 'Verification Stage',
      content: [
        'Prove consistency with relaxed profit targets to move to funded.',
      ],
      isUnlock: true,
      isActive: true,
    },
  ],

  CustomTradingStats: {
    Trading_Stats: [
      {
        title: English.E61,
        firstContent: '3000',
        secondContent: '3120',
        mainType: 'lablelType',
        subType: '',
        isProgressBarType: false,
      },
      {
        title: English.E62,
        firstContent: '---',
        secondContent: '---',
        subType: '',
        mainType: 'lablelType',
        isProgressBarType: false,
      },
      {
        title: English.E63,
        firstContent: '5995.23',
        subType: '',
        mainType: 'normalType',
        isProgressBarType: false,
      },
    ],

    [English.E64]: [
      {
        title: English.E66,
        firstContent: '5',
        secondContent: '0',
        mainType: 'winProgressType',
        subType: 'days',
        isProgressBarType: true,
      },
      {
        title: English.E68,
        firstContent: '500',
        secondContent: '0',
        mainType: 'winProgressType',
        subType: 'money',
        isProgressBarType: true,
      },
      {
        title: English.E69,
        firstContent: '500',
        secondContent: '0',
        mainType: 'lossProgressType',
        subType: 'money',
        isProgressBarType: true,
      },
      {
        title: English.E70,
        firstContent: '1000',
        secondContent: '0',
        mainType: 'lossProgressType',
        subType: 'loss_money',
        isProgressBarType: true,
      },
    ],

    [English.E71]: [
      {
        title: English.E72,
        firstContent: '0',
        mainType: 'longShortType',
        subType: '',
        isProgressBarType: false,
      },
      {
        title: English.E73,
        firstContent: '0',
        mainType: 'winLossType',
        subType: '',
        isProgressBarType: false,
      },
      {
        title: English.E74,
        firstContent: '0',
        mainType: 'normalMoneyType',
        subType: 'win_rate',
        isProgressBarType: false,
      },
      {
        title: English.E79,
        firstContent: '0',
        mainType: 'normalMoneyType',
        subType: 'win_rate',
        isProgressBarType: false,
      },
    ],
  },
  ClosedPNL: [
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.5,
      entryValue: '12,500 USDT',
      exitValue: '12,750 USDT',
      entryPrice: '25,000',
      exitPrice: '25,500',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.51,
      entryValue: '15,000 USDT',
      exitValue: '12,750 USDT',
      entryPrice: '12,902',
      exitPrice: '25,200',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.23,
      entryValue: '9,500 USDT',
      exitValue: '189 USDT',
      entryPrice: '25,000',
      exitPrice: '25,500',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
    {
      contract: 'BTC-USDT',
      closingDirection: 'Long → Closed',
      qty: 0.19,
      entryValue: '1,500 USDT',
      exitValue: '12 USDT',
      entryPrice: '43,199',
      exitPrice: '43,199',
      closedPnL: '+250.00 USDT',
      filledType: 'Market Order',
    },
  ],
  CertificateTabHeading: [
    {title: English.E91, img: ''},
    {title: English.E92, img: ''},
    {title: English.E93, img: ''},
  ],
  Certificate: {
    CertificatesBodyData: [
      {
        certificateId: 'CT-2025-001',
        challengeName: 'Two-Step Challenge',
        tradingCapital: '1000',
        status: '✅ Passed',
        issueDate: '2025-09-10',
        action: 'Download',
      },
      {
        certificateId: 'CT-2025-002',
        challengeName: 'One-Step Challenge',
        tradingCapital: '25000',
        status: '🎯 Profit Target',
        issueDate: '2025-08-28',
        action: 'Download',
      },
      {
        certificateId: 'CT-2025-003',
        challengeName: 'Free Trial',
        tradingCapital: '5000',
        status: '✅ Passed',
        issueDate: '2025-07-15',
        action: 'Download',
      },
    ],
    CertificatesHeadingData: [
      {content: [English.E94], showArrow: false},
      {content: [English.E95], showArrow: false},
      {content: [English.E96], showArrow: false},
      {content: [English.E52], showArrow: false},
      {content: [English.E98], showArrow: false},
      {content: [English.E99], showArrow: false},
    ],
  },
  Payout: {
    PayoutTableBodyData: [
      {
        payoutId: 'P-2025-001',
        date: '2025-09-05',
        amount: '10000',
        status: '✅ Paid',
        method: 'USDT (Wallet)',
        transactionId: '0x93f...a82c',
      },
      {
        payoutId: 'P-2025-002',
        date: '2025-08-20',
        amount: '25000',
        status: '✅ Paid',
        method: 'USDT (Wallet)',
        transactionId: '0x93f...a82c',
      },
    ],
    PayoutTableHeadingData: [
      {content: [English.E103], showArrow: false},
      {content: [English.E104], showArrow: false},
      {content: [English.E105], showArrow: false},
      {content: [English.E52], showArrow: false},
      {content: [English.E107], showArrow: false},
      {content: [English.E108], showArrow: false},
    ],
  },
  Billing: {
    BillingTableBodyData: [
      {
        invoiceId: 'P-2025-001',
        date: '2025-09-05',
        challenge: 'Two-Step',
        plan: 'Initiater',
        amount: '$69',
        status: '✅ Paid',
        transactionId: '0x93f...a82c',
        action: 'Download',
      },
      {
        invoiceId: 'P-2025-002',
        date: '2025-08-20',
        challenge: 'One-Step',
        plan: 'Strategist',
        amount: '$249',
        status: '🚫 Failed',
        transactionId: '0x93f...a82c',
        action: 'Download',
      },
    ],
    BillingTableHeadingData: [
      {content: [English.E111], showArrow: false},
      {content: [English.E104], showArrow: false},
      {content: [English.E97], showArrow: false},
      {content: [English.E106], showArrow: false},
      {content: [English.E105], showArrow: false},
      {content: [English.E52], showArrow: false},
      {content: [English.E108], showArrow: false},
      {content: [English.E99], showArrow: false},
    ],
  },
  ChallengesTabContent: [
    {title: English.E114, content: English.E33},
    {title: English.E115, content: English.E34},
    {title: English.E116, content: English.E35},
  ],
  ConstantChallengeData: {
    Status: 'Ongoing',
    'Current balance': '10,000',
    'Minimum Trading Days': '5',
    Challenge: 'Two Step',
    'Trading type': 'Futures',
    'Drawdown type': 'Trailing',
    'Challenge type': 'Zeno Challenger',
  },
  ChartTypes: [
    {key: '1m', content: English.E137},
    {key: '3m', content: English.E227},
    {key: '5m', content: English.E228},
    {key: '15m', content: English.E229},
    {key: '30m', content: English.E230},
    {key: '1h', content: English.E123},
    {key: '4h', content: English.E124},
    {key: '1d', content: English.E125},
    {key: '1month', content: English.E231},
  ],
  BuySellInputArray: {
    Market: [
      {
        name: 'price',
        placeHolder: English.E131,
        textContent: English.E60,
      },
      {
        name: 'amount',
        placeHolder: English.E105,
        textContent: 'BTC',
      },
      {
        name: 'total',
        placeHolder: English.E133,
        textContent: 'BTC',
      },
    ],
    Limit: [
      {
        name: 'entryprice',
        placeHolder: 'Entery Price',
        textContent: English.E60,
        label: 'Entry Price',
      },
      {
        name: 'quantity',
        placeHolder: 'Quantity',
        textContent: '0ETH',
        label: 'Quantity',
      },
    ],
    SLTP: [
      {
        name: 'marketprice',
        placeHolder: 'Entery Market Price',
        textContent: English.E60,
        label: 'Entry Market Price',
      },
      {
        name: 'closingquantity',
        placeHolder: 'Quantity',
        textContent: '0ETH',
        label: 'Closing Quantity',
      },
    ],
  },
  BuySellActionButtons: [
    [
      {name: 'buy', text: English.E134},
      {name: 'sell', text: English.E135},
    ],
    [
      {name: 'buy', text: 'Buy'},
      {name: 'sell', text: 'Sell'},
    ],
  ],
  TradingTab: [{title: English.E136}],
  ChartSwitchType: ['buy_sell_type', 'buy_type', 'sell_type'],
  tradesHeadingTypes: [
    {title: English.E142},
    {title: English.E143},
    {title: English.E344},
    {title: English.E144},
    {title: English.E345},
  ],
  orderMarginMode: [{title: English.E139}, {title: English.E329}],
  trades: [
    {
      id: 1,
      time: '2025-10-11T18:05:40.000Z',
      price: 36641.20973578,
      amount: 0.2454545454545,
      total: 8985.04,
      type: 'buy',
    },
    {
      id: 2,
      time: '2025-10-11T18:05:39.000Z',
      price: 35562.20973578,
      amount: 0.254787846482,
      total: 9063.27,
      type: 'buy',
    },
    {
      id: 3,
      time: '2025-10-11T18:05:38.000Z',
      price: 36641.20973578,
      amount: 0.188888888888,
      total: 6921.15,
      type: 'buy',
    },
    {
      id: 4,
      time: '2025-10-11T18:05:40.100Z',
      price: 36641.20973578,
      amount: 1.0,
      total: 36641.2,
      type: 'buy',
    },
    {
      id: 11,
      time: '2025-10-11T18:05:41.000Z',
      price: 36645.10973578,
      amount: 0.5,
      total: 18322.55,
      type: 'sell',
    },
    {
      id: 12,
      time: '2025-10-11T18:05:42.000Z',
      price: 36650.00973578,
      amount: 0.8,
      total: 29320.01,
      type: 'sell',
    },
    {
      id: 15,
      time: '2025-10-11T18:05:45.000Z',
      price: 36652.90973578,
      amount: 0.6,
      total: 21991.75,
      type: 'sell',
    },
  ],
  chartTools: [
    {img: Images.cursor, name: 'cursor'},
    {img: Images.trendLine, name: 'trend_line'},
    {img: Images.multiLine, name: 'multi_line'},
    {img: Images.multiRange, name: 'multi_range'},
  ],
  pickAPlan: ['Pick a Plan', 'Payment & Success'],
  detailedTradeHistory: ['Detailed Trade History', 'Performance Insights'],
  challengeType: [Images.challengeType, Images.summary],
  professionalImgs: [Images.professional, Images.professionalTwo],

  QA: [
    {
      que: 'What is a trading challenge?',
      ans: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime neque dolore esse ipsam culpa, qui accusantium veniam quis? Vitae similique adipisci consectetur ad in nam quisquam fugit non id earum eligendi, aliquam consequuntur quod dolor inventore. Reprehenderit, itaque minima quidem veniam voluptates atque culpa voluptatibus sequi, facilis, dicta nam sed. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime neque dolore esse ipsam culpa, qui accusantium veniam quis? Vitae similique adipisci consectetur ad in nam quisquam fugit non id earum eligendi, aliquam consequuntur quod dolor inventore. Reprehenderit, itaque minima quidem veniam voluptates atque culpa voluptatibus sequi, facilis, dicta nam sed.',
    },
    {
      que: 'Can I trade any strategy or style I prefer?',
      ans: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime neque dolore esse ipsam culpa, qui accusantium veniam quis? Vitae similique adipisci consectetur ad in nam quisquam fugit non id earum eligendi, aliquam consequuntur quod dolor inventore. Reprehenderit, itaque minima quidem veniam voluptates atque culpa voluptatibus sequi, facilis, dicta nam sed.',
    },
    {
      que: 'Do I risk my own money?',
      ans: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime neque dolore esse ipsam culpa, qui accusantium veniam quis? Vitae similique adipisci consectetur ad in nam quisquam fugit non id earum eligendi, aliquam consequuntur quod dolor inventore. Reprehenderit, itaque minima quidem veniam voluptates atque culpa voluptatibus sequi, facilis, dicta nam sed.',
    },
    {
      que: 'What happens after I pass the challenge?',
      ans: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime neque dolore esse ipsam culpa, qui accusantium veniam quis? Vitae similique adipisci consectetur ad in nam quisquam fugit non id earum eligendi, aliquam consequuntur quod dolor inventore. Reprehenderit, itaque minima quidem veniam voluptates atque culpa voluptatibus sequi, facilis, dicta nam sed.',
    },
    {
      que: 'How long do I get to complete the challenge?',
      ans: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime neque dolore esse ipsam culpa, qui accusantium veniam quis? Vitae similique adipisci consectetur ad in nam quisquam fugit non id earum eligendi, aliquam consequuntur quod dolor inventore. Reprehenderit, itaque minima quidem veniam voluptates atque culpa voluptatibus sequi, facilis, dicta nam sed.',
    },
    {
      que: 'How is V7 Go different from V7 Darwin?',
      ans: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime neque dolore esse ipsam culpa, qui accusantium veniam quis? Vitae similique adipisci consectetur ad in nam quisquam fugit non id earum eligendi, aliquam consequuntur quod dolor inventore. Reprehenderit, itaque minima quidem veniam voluptates atque culpa voluptatibus sequi, facilis, dicta nam sed.',
    },
  ],

  footerLinks: [
    {
      title: 'Zeno',
      links: ['Overview', 'About', 'Finance', 'Legal'],
    },
    {
      title: 'Resources',
      links: ['Blog', 'ChangeLog', 'Webinar', 'Security', 'Customer stories'],
    },
    {
      title: 'Company',
      links: ['About', 'Careers', 'News', 'Contact'],
    },
  ],
  socialLinks: [
    {
      title: 'Legal',
      links: ['Terms', 'Privacy Policy', 'Cookie Declaration'],
    },
    {
      title: 'Social',
      links: ['LinkedIn', 'YouTube', 'X (Twitter)', 'GitHub'],
    },
  ],
  brandImages: [
    Images.ablCorporation,
    Images.alp4,
    Images.mercedez,
    Images.sony,
    Images.roche,
    Images.paige,
  ],

  featuresParagraphContent1: [
    'Follow clear, structured steps to begin your ',
    'challenge, track performance, and unlock ',
    'funded trading.',
  ],

  zenoCards: [
    {
      id: 1,
      logo: Images.zenoOrange,
      heading: English.E157,
      subHeading: English.E160,
      tags: [English.E163, English.E164, English.E165],
    },
    {
      id: 2,
      logo: Images.zenoPurple,
      heading: English.E158,
      subHeading: English.E161,
      tags: [English.E166, English.E167, English.E168],
    },
    {
      id: 3,
      logo: Images.zenoGreen,
      heading: English.E159,
      subHeading: English.E162,
      tags: [English.E169, English.E170, English.E171],
    },
    {
      id: 4,
      logo: Images.zenoOrange,
      heading: English.E157,
      subHeading: English.E160,
      tags: [English.E163, English.E164, English.E165],
    },
    {
      id: 5,
      logo: Images.zenoPurple,
      heading: English.E158,
      subHeading: English.E161,
      tags: [English.E166, English.E167, English.E168],
    },
    {
      id: 6,
      logo: Images.zenoGreen,
      heading: English.E159,
      subHeading: English.E162,
      tags: [English.E169, English.E170, English.E171],
    },
  ],

  challengeArray: [English.E148, English.E175, English.E176],

  tradeNTrackArray: [English.E151, English.E177, English.E178],

  fundNWithdrawArray: [English.E179, English.E22],

  featuresObjectLg: [
    {
      id: 1,
      logo: Images.platformLogo,
      size: 'w-3.5 h-[13px] ml-1',
      content: English.E181,
      idToScroll: 'challenge_container',
    },
    {
      id: 2,
      logo: Images.tradeNTrackLg,
      size: 'size-[19px]',
      content: English.E149,
      idToScroll: 'trade_track_container',
    },
    {
      id: 3,
      logo: Images.fundNWithdrawLg,
      size: 'size-[19px]',
      content: English.E150,
      idToScroll: 'fund_and_withdraw',
    },
  ],

  OneStepTwoStepArray: [English.E182, English.E183],

  featuresWholeArray: [
    {
      id: 'challenge_container',
      logo: Images.platformLogo,
      heading: English.E97,
      subHeading: English.E172,
      para: English.E184,
      options: [English.E175, English.E176],
      optionsLg: [
        {
          parentId: 1,
          heading: English.E148,
          subHeading: English.E233,
          content: English.E188,
          image: Images.featureChallenge1,
          containerHeading: English.E148,
        },
        {
          parentId: 1,
          heading: English.E175,
          subHeading: English.E234,
          content: English.E244,
          image: Images.featureChallenge2,
          containerHeading: English.E175,
        },
        {
          parentId: 1,
          heading: English.E176,
          subHeading: English.E235,
          content: English.E245,
          image: Images.featureChallenge3,
          containerHeading: English.E176,
        },
      ],
      cardHeading: English.E148,
      cardSubHeading: English.E153,
      cardPara: English.E188,
    },

    {
      id: 'trade_track_container',
      logo: Images.tradeNTrack,
      heading: English.E149,
      subHeading: English.E173,
      para: English.E184,
      options: [English.E177, English.E178],
      optionsLg: [
        {
          heading: English.E151,
          parentId: 2,
          subHeading: English.E236,
          content: English.E246,
          image: Images.featureTradTrack1,
          containerHeading: English.E151,
        },
        {
          heading: English.E177,
          parentId: 2,
          subHeading: English.E237,
          content: English.E247,
          image: Images.featureTradTrack2,
          containerHeading: English.E177,
        },
        {
          heading: English.E178,
          parentId: 2,
          subHeading: English.E238,
          content: English.E248,
          image: Images.featureTradTrack3,
          containerHeading: English.E178,
        },
      ],
      cardHeading: English.E151,
      cardSubHeading: English.E154,
      cardPara: English.E189,
      cardSpan: English.E192,
    },
    {
      id: 'fund_and_withdraw',
      logo: Images.fundNWithdraw,
      heading: English.E150,
      subHeading: English.E174,
      para: English.E190,
      options: [English.E22],

      optionsLg: [
        {
          heading: English.E179,
          parentId: 3,
          subHeading: English.E239,
          para: English.E239,
          content: English.E249,
          image: Images.featureFundsAndWithdraw1,
          containerHeading: English.E242,
        },
        {
          heading: English.E22,
          parentId: 3,
          subHeading: English.E240,
          para: English.E240,
          content: English.E250,
          image: Images.featureFundsAndWithdraw2,
          containerHeading: English.E241,
        },
      ],
      cardHeading: English.E152,
      cardSubHeading: English.E155,
      cardPara: English.E191,
    },
  ],

  carouselOptions: [
    {content: English.E193, sliderId: 1},
    {content: English.E194, sliderId: 2},
    {content: English.E195, sliderId: 3},
  ],

  HomePageNavbarContent: [
    {linkTo: '/', content: English.E198},
    {linkTo: '/', content: English.E199},
    {linkTo: '/', content: English.E200},
  ],

  StepComponentHeading: [{title: English.E182}, {title: English.E183}],
  Openposition: [
    {content: [English.E275], showArrow: false},
    {content: [English.E180], showArrow: false},
    {content: [English.E271], showArrow: false},
    {content: [English.E262], showArrow: false},
    {content: [English.E264], showArrow: false},
    {content: [English.E265], showArrow: false},
    {content: [`${English.E269} ${English.E268}`], showArrow: false},
    {content: [English.E269], showArrow: false},
    {content: [English.E298], showArrow: false},
    {content: [`${English.E62}(${English.E289})`], showArrow: false},
    {content: [English.E243], showArrow: false},
  ],
  PendingOrders: [
    {content: [English.E275], showArrow: false},
    {content: [English.E180], showArrow: false},
    {content: [English.E270], showArrow: false},
    {content: [English.E271], showArrow: false},
    {content: [English.E299], showArrow: false},
    {content: [English.E300], showArrow: false},
    {content: [English.E298], showArrow: false},
    {content: [English.E295], showArrow: false},
  ],
  ClosedPNLTableHeading: [
    {content: [English.E275], showArrow: false},
    {content: [English.E276], showArrow: false},
    {content: [English.E278], showArrow: false},
    {content: [English.E281], showArrow: false},
    {content: [English.E282], showArrow: false},
    {content: [English.E283], showArrow: true},
    {content: [English.E284], showArrow: true},
    {content: [English.E285], showArrow: false},
    {content: [English.E286], showArrow: false},
  ],
  OpenHistoryTableHeading: [
    {content: [English.E275], showArrow: false},
    {content: [English.E334], showArrow: false},
    {content: [English.E270], showArrow: false},
    {content: [English.E335, English.E336], showArrow: false},
    {content: [`${English.E105} | ${English.E105}`], showArrow: false},
    {content: [English.E337, English.E338], showArrow: false},
    {content: [English.E339], showArrow: false},
    {content: [English.E340], showArrow: false},
    {content: [English.E52], showArrow: false},
  ],
  PositionHistoryTableHeading: [
    {content: [English.E275], showArrow: false},
    {content: [English.E346], showArrow: false},
    {content: [English.E347], showArrow: false},
    {content: [English.E270], showArrow: false},
    {content: [English.E335, English.E348], showArrow: false},
    {content: [English.E349, `${English.E338}%`], showArrow: false},
    {content: [English.E350], showArrow: false},
    {content: [English.E339], showArrow: false},
    {content: [English.E298], showArrow: false},
  ],

  TransactionDetailsHistoryTableHeading: [
    {content: [English.E275], showArrow: false},
    {content: [English.E334], showArrow: false},
    {content: [English.E270], showArrow: false},
    {content: [English.E351], showArrow: false},
    {content: [English.E105], showArrow: false},
    {content: [English.E353], showArrow: false},
    {content: [English.E339], showArrow: false},
  ],
  PlaceOrderTab: [
    {title: English.E290, img: ''},
    {title: English.E131, img: ''},
  ],
}

export default Constants
