const English = {
  E1: 'Your Gateway to Funded Trading',
  E2: 'Login to your Zeno account',
  E3: 'Email ID',
  E4: 'Enter your email id',
  E5: 'Password',
  E6: 'Enter password',
  E7: 'Sign in',
  E8: 'Sign in with Google',
  E9: 'Don’t have account?',
  E10: 'Create New',
  E11: 'Your Trading Workspace',
  E12: 'Create your Zeno account',
  E13: 'Already have account?',
  E14: 'Create Account',
  E15: 'Full Name',
  E16: 'Enter your full name',
  E17: 'Re-Password',
  E18: 'Re Enter password',
  E19: 'Create Challenge',
  E20: 'Zeno Trader',
  E21: 'Challenges',
  E22: 'Certificates',
  E23: 'Payout',
  E24: 'Billing',
  E25: 'My Profile',
  E26: 'Create and track your trading challenges. Start with your first one below.',
  E27: 'Challenge Type',
  E28: 'No challenges yet.',
  E29: 'Start your first challenge to unlock funded trading.',
  E30: 'Logout',
  E31: 'Select how you want to qualify for a funded account. Each type has different rules and requirements.',
  E32: 'One-Step',
  E33: 'Reach your funded account faster with just one phase. Simple rules, quicker access.',
  E34: 'Two-Step',
  E35: 'Traditional evaluation with Stage 1 and Stage 2 targets. Stricter rules but lower risk.',
  E36: 'Challenge Name',
  E37: 'Account Size',
  E38: 'Capital Fund',
  E39: 'Trading Capital',
  E40: 'Pick your preferred account size. Larger accounts require higher entry fees but unlock bigger earning potential.',
  E41: 'Summary',
  E42: 'Your challenge includes',
  E43: '✅ Up to 90% Performance Rewards',
  E44: '✅ Zero Real Financial Risk',
  E45: '✅ Dedicated Personal Support',
  E46: '✅ Multiple Account Sizes & Paths to Funding',
  E47: 'Pay Now',
  E48: '⚡ Select a challenge type and account size to view pricing and details.',
  E49: 'Payment Successful!',
  E50: 'You’ve successfully purchased the Initiater Challenge ($5,000 account) for $69.',
  E51: 'Payment',
  E52: 'Status',
  E53: 'Start date',
  E54: 'View Dashboard',
  E55: 'Zeno Challenger',
  E56: 'Trade',
  E57: 'Current Status',
  E58: 'Current',
  E59: 'Initial Capital',
  E60: 'USDT',
  E61: 'Released Profit',
  E62: 'Unreleased Profit',
  E63: 'Equity',
  E64: 'Trading Objective',
  E65: 'Trading Statistics',
  E66: 'Trading Days',
  E67: 'Days',
  E68: 'Profit Target',
  E69: 'Daily Drawdown',
  E70: 'Max. Loss',
  E71: 'Trading Statistics',
  E72: 'Total Closed trades',
  E73: 'Win rate of closed trades',
  E74: 'Long',
  E75: 'Short',
  E76: 'Win',
  E77: 'Loss',
  E78: 'Win rate of closed trades',
  E79: 'P&L of closed long orders',
  E80: 'Win rate',
  E81: 'Closed PnL',
  E82: 'Legend',
  E83: '•   Trade count towards',
  E84: 'Trading Days',
  E85: 'Clear',
  E86: 'Please enter valid Email ID',
  E87: 'Password does not Match.',
  E88: 'Start New Challenge',
  E89: 'Choose your challenge type, select trading capital, and begin your journey to a funded account.',
  E91: 'All',
  E92: 'Profit',
  E93: 'Passed',
  E94: 'Certificate ID',
  E95: 'Challenge Name',
  E96: 'Trading Capital',
  E97: 'Challenge',
  E98: 'Issue Date',
  E99: 'Download',
  E100: 'Pending Payout',
  E101: 'Next payout on',
  E102: 'Payout History',
  E103: 'Payout ID',
  E104: 'Date',
  E105: 'Amount',
  E106: 'Plan',
  E107: 'Method',
  E108: 'Transaction ID',
  E109: 'Billing',
  E110: 'Track all completed payments and billing activity here.',
  E111: 'Invoice ID',
  E112: 'Profile',
  E113: 'Save',
  E114: 'Ongoing',
  E115: 'Failed',
  E116: 'Expired',
  E117: 'ID',
  E118: 'Show Details',
  E119: '24h change',
  E120: '24h high',
  E121: '24h low',
  E122: '24h volume',
  E123: '1H',
  E124: '4H',
  E125: '1D',
  E126: '1W',
  E127: '1M',
  E128: 'Time',
  E129: 'Place order',
  E130: 'Available',
  E131: 'Market',
  E132: 'Perpetual',
  E133: 'Total',
  E134: 'Buy / Long',
  E135: 'Sell / Short',
  E136: 'Order Book',
  E137: '1m',
  E138: 'Start Your Challenge',
  E139: 'isolated',
  E140: 'Price',
  E141: 'Amounts',
  E142: 'Open Position',
  E143: 'Pending Orders',
  E144: 'Position History',
  E145: 'Currepted Positions',
  E146: 'Transaction Details',
  E147: 'Transaction History',
  E148: 'Choose Type',
  E149: 'Trade & Track',
  E150: 'Fund & Withdraw',
  E151: 'Real-time dashboard',
  E152: 'Withdraw your profits',
  E153: 'One-Step or Two-Step to begin your journey.',
  E154: 'Track your trading objectives at a glance.',
  E155: 'Fast, transparent, and secure payouts.',
  E156: ' No guesswork, just clarity.',
  E157: 'Freedom',
  E158: 'Clarity',
  E159: 'Growth',
  E160: 'Trade Without Limits',
  E161: 'Transparent & Real-Time',
  E162: 'Fast & Scalable Rewards',
  E163: 'All Major Crypto Pairs',
  E164: 'No Time Limits',
  E165: 'Direct Trading on Zeno Panel',
  E166: 'Simple and Transparent Rules',
  E167: 'Risk Management',
  E168: 'Performance Tracking Live',
  E169: '48h Withdrawals',
  E170: 'Scalable Accounts',
  E171: 'High Reward Profit Payouts',
  E172: 'Design your AI workflows step by step.',
  E173: 'Trade with clarity, control and performance tracking.',
  E174: 'Withdrawl profits and earn certificates that validate your trading skills.',
  E175: 'Pick a Plan',
  E176: 'Payment & Success',
  E177: 'Detailed Trade History',
  E178: 'Performance Insights',
  E179: 'Payouts',
  E180: 'Open',
  E181: 'Start a Challenge',
  E182: 'One Step',
  E183: 'Two Step',
  E184: 'Follow clear, structured steps to begin your challenge, track performance, and unlock funded trading.',
  E185: 'Trusted by',
  E186: 'More stories',
  E187: 'thousands of traders worldwide',
  E188: 'Pick between our challenge models. One-Step is faster with a single evaluation target. Two-Step offers a gradual verification with relaxed second-stage rules. Both help you qualify for a funded account.',
  E189: 'Zeno’s dashboard shows your profit targets, daily drawdown, max loss, and trading days, all updated in real time.',
  E190: 'With Zeno, your effort is recognized both financially and professionally. ',
  E191: 'Zeno makes withdrawing your profits simple. Track transactions, and receive funds directly in USDT in your wallet.',
  E192: ' No guesswork, just clarity',
  E193: 'Professional Trader',
  E194: 'Part-time Trader',
  E195: 'Beginner Trader',
  E196: 'Log in',
  E197: 'Create new account',
  E198: 'Product',
  E199: 'About Us',
  E200: 'Resources',
  E201: 'Start Your Journey with Zeno',
  E202: 'Choose your challenge type and account size, complete the Zeno Trading Challenge, and prove your ability to trade consistently under professional conditions. Trade in a simulated environment with up to 200,000 USDT in virtual capital and unlock the path to a funded account.',
  E203: 'Trade. Get Funded. Earn.',
  E204: 'Unlock Capital. Scale up-to 200K.',
  E205: 'Keep Profits. Withdraw Anytime.',
  E206: 'Zeno Trading + Funding Hub',
  E207: `The Zeno Crypto Prop Trading Suite combines the #1 Trading Challenges with
                instant Funding, built on one powerful platform that empowers traders and
                unlocks lasting profits.`,
  E208: 'When your dream of financial freedom depends on consistent results,',
  E209: 'giving up isn’t an option.',
  E210: 'Features',
  E211: 'Start a Challenge in Minutes.',
  E212: 'Funding Up to 200K',
  E213: 'Rules',
  E214: 'Trading Rules of Zeno',
  E215: `Follow Zeno’s transparent trading rules to qualify for and
                maintain your funded account. These rules are designed to build
                discipline, protect capital, and help serious traders achieve
                long-term success with professional funding.`,
  E216: 'FAQs',
  E217: 'Have questions?',
  E218: 'Find answers.',
  E219: 'Any more questions?',
  E220: 'Talk to sales',
  E221: 'Subscribe to the',
  E222: 'Zeno Newsletter',
  E223: 'Stop wasting years proving yourself in risky trading environments',
  E224: 'Stage 1',
  E225: 'Stage 2',
  E226: 'Final',
  E227: '3M',
  E228: '5M',
  E229: '15M',
  E230: '30M',
  E231: '1M',
  E232: 'Copied to clipboard',
  E233: 'One-Step or Two-Step to begin your journey.',
  E234: 'Select your preferred account size and challenge fees.',
  E235: 'Complete your payment and activate your challenge instantly.',
  E236: 'Track your trading objectives at a glance.',
  E237: 'Review every trade with precise clarity.',
  E238: 'Advanced analytics to elevate your trading skills.',
  E239: 'Fast, transparent, and secure payouts.',
  E240: 'Your trading performance, officially recognized.',
  E241: 'Earn certificates for every milestone',
  E242: 'Withdraw your profits',
  E244: 'Choose from multiple account sizes starting at 5,000 USDT and scaling up to 200,000 USDT. Each plan includes transparent rules, fixed fees, and no hidden conditions. Pick the account size that aligns with your trading confidence and growth goals.',
  E245: 'Secure your challenge with a quick, seamless checkout. Your account is activated immediately, and you can start trading without delay. Once you achieve the targets, your certificate is issued and your funded account goes live.',
  E246: 'Zeno’s dashboard shows your profit targets, daily drawdown, max loss, and trading days, all updated in real time. No guesswork, just clarity.',
  E247: 'Zeno records every trade you place, timestamp, direction, entry value, exit value, profit/loss, and order type. Your full trading journal updates automatically, helping you spot patterns, avoid mistakes, and refine your strategy with real evidence.',
  E248: 'Track win rate, long vs. short performance, average R/R, best and worst trades, and consistency metrics, all generated automatically. Zeno turns your raw data into meaningful insights so you can optimize your trading and progress through challenges with confidence.',
  E249: 'Zeno makes withdrawing your profits simple. Track transactions, and receive funds directly in USDT in your wallet.',
  E250: 'Each time you pass a challenge stage or reach important milestones, Zeno issues a certificate confirming your performance. Download, share, or use it to validate your trading skills for future opportunities — both inside and outside Zeno.',
  E251: 'Verification Stage',
  E252: 'Demo evaluation passed',
  E253: 'Prove consistency with relaxed profit targets to move to funded.',
  E254: '🔒 Live funded account unlocked after passing Stage.',
  E255: 'Stage',
  E256: 'Live funded account unlocked after passing Stage 2.',
  E257: 'Trading_Stats',
  E258: 'P&L of closed short orders',
  E243: 'Close',
  E259: 'lossProgressType',
  E260: 'Asset',
  E261: 'Direction',
  E262: 'Average price',
  E263: 'Duration',
  E264: 'Mark Price',
  E265: 'Est. Liq. Price',
  E266: 'Next TP',
  E267: 'Next SL',
  E268: 'Ratio',
  E269: 'Margin',
  E270: 'Slide',
  E271: 'Quantity',
  E272: 'Submitted Price',
  E273: '',
  E274: 'Expiration',
  E275: 'Contracts',
  E276: 'Closing Direction',
  E278: 'Qty',
  E279: 'Insufficient Funds',
  E280: 'Placed Order Successfully',
  E281: 'Entry Value',
  E282: 'Exit Value',
  E283: 'Entry Price',
  E284: 'Exit Price',
  E285: 'Closed Type',
  E286: 'Filled Type',
  E287: 'Select Date',
  E288: 'No Data Found!',
  E289: 'ROE',
  E290: 'Limit',
  E291: 'Current Distance',
  E292: 'Stop Loss',
  E293: ' Market Price',
  E294: ' Closing Quantity',
  E295: 'Delete',
  E296: 'Stop Loss must be LESS than Live Price And Take Profit must be GREATER than Live Price for BUY order ',
  E297: 'Stop Loss must be GREATER than Live Price And Take Profit must be LESS than Live Price for SELL order ',
  E298: 'TP/SL',
  E299: 'Order Price',
  E300: 'Position Margin',
  E317: 'Max Open',
  E318: 'Cost',
  E319: 'Margin',
  E320: 'Assets',
  E321: 'Available Margin',
  E322: 'Used Margin',
  E323: 'Total Balance',
  E324: 'Account Balance',
  E325: 'Unreleased PNL',
  E326: 'Available Margin',
  E327: 'Used Margin',
  E301: 'Forgot Password',
  E302: 'Reset Your Zeno Account Password',
  E303: 'Send OTP',
  E304: 'Back To Login',
  E305: 'Please Enter Valid Email',
  E306: 'Email OTP',
  E307: 'Enter Your OTP',
  E308: 'Change Password',
  E309: 'Confirm Password',
  E310: 'Enter Confirm Password',
  E311: 'New Password',
  E312: 'Enter New Password',
  E313: 'Please enter your Zeno Traders Email and follow the link sent to your email to update your password.',
  E314: 'Set Your New Zeno Trader Password',
  E315: 'Enter Otp You Recieved in Your Email And Set Your New Password',
  E316: 'Enter a valid 6-digit OTP using numbers only',
  E328: 'Password must include 1 uppercase, 1 number, 1 special, and it must be 8 characters.',
  E329: 'cross',
  E330: 'Verify OTP',
  E331: 'Certificate Download',
  E332: 'Current Stage',
  E333: 'Update TP/SL',
}

export default English
