const English = {
  E1: 'Your Gateway to Funded Trading',
  E2: 'Login to your Zeno account',
  E3: 'Email ID',
  E4: 'Enter your email id',
  E5: 'Password',
  E6: 'Enter password',
  E7: 'Sign in',
  E8: 'Sign in with Google',
  E9: 'Don’t have account?',
  E10: 'Create New',
  E11: 'Your Trading Workspace',
  E12: 'Create your Zeno account',
  E13: 'Already have account?',
  E14: 'Create Account',
  E15: 'Full Name',
  E16: 'Enter your full name',
  E17: 'Re-Password',
  E18: 'Re Enter password',
  E19: '+ Create Challenge',
  E20: 'Zeno Trader',
  E21: 'Challenges',
  E22: 'Certificates',
  E23: 'Payout',
  E24: 'Billing',
  E25: 'My Profile',
  E26: 'Create and track your trading challenges. Start with your first one below.',
  E27: 'Challenge Type',
  E28: 'No challenges yet.',
  E29: 'Start your first challenge to unlock funded trading.',
  E30: 'Logout',
  E31: 'Select how you want to qualify for a funded account. Each type has different rules and requirements.',
  E32: 'One-Step',
  E33: 'Reach your funded account faster with just one phase. Simple rules, quicker access.',
  E34: 'Two-Step',
  E35: 'Traditional evaluation with Stage 1 and Stage 2 targets. Stricter rules but lower risk.',
  E36: 'Challenge Name',
  E37: 'Account Size',
  E38: 'Capital Fund',
  E39: 'Trading Capital',
  E40: 'Pick your preferred account size. Larger accounts require higher entry fees but unlock bigger earning potential.',
  E41: 'Summary',
  E42: 'Your challenge includes',
  E43: '✅ Up to 90% Performance Rewards',
  E44: '✅ Zero Real Financial Risk',
  E45: '✅ Dedicated Personal Support',
  E46: '✅ Multiple Account Sizes & Paths to Funding',
  E47: 'Pay Now',
  E48: '⚡ Select a challenge type and account size to view pricing and details.',
  E49: 'Payment Successful!',
  E50: 'You’ve successfully purchased the Initiater Challenge ($5,000 account) for $69.',
  E51: 'Payment',
  E52: 'Status',
  E53: 'Start date',
  E54: 'View Dashboard',
  E55: 'Zeno Challenger',
  E56: 'Trade',
  E57: 'Current Status',
  E58: 'Current',
  E59: 'Initial Capital',
  E60: 'USDT',
  E61: 'Released Profit',
  E62: 'Unreleased Profit',
  E63: 'Equity',
  E64: 'Trading Objective',
  E65: 'Trading Statistics',
  E66: 'Trading Days',
  E67: 'Days',
  E68: 'Profit Target',
  E69: 'Daily Drawdown',
  E70: 'Max. Loss',
  E71: 'Trading Statistics',
  E72: 'Total Closed trades',
  E73: 'Win rate of closed trades',
  E74: 'Long',
  E75: 'Short',
  E76: 'Win',
  E77: 'Loss',
  E78: 'Win rate of closed trades',
  E79: 'P&L of closed long orders',
  E80: 'Win rate',
  E81: 'Closed PnL',
  E82: 'Legend',
  E83: '•   Trade count towards',
  E84: 'Trading Days',
  E85: 'Clear',
  E86: 'Please Enter Proper Email',
  E87: 'Password does not Match.',
  E88: 'Start New Challenge',
  E89: 'Choose your challenge type, select trading capital, and begin your journey to a funded account.',
  E90: 'Certificates',
  E91: 'All',
  E92: 'Profit',
  E93: 'Passed',
  E94: 'Certificate ID',
  E95: 'Challenge Name',
  E96: 'Trading Capital',
  E97: 'Challenge',
  E98: 'Issue Date',
  E99: 'Action',
  E100: 'Pending Payout',
  E101: 'Next payout on',
  E102: 'Payout History',
  E103: 'Payout ID',
  E104: 'Date',
  E105: 'Amount',
  E106: 'Plan',
  E107: 'Method',
  E108: 'Transaction ID',
  E109: 'Billing',
  E110: 'Track all completed payments and billing activity here.',
  E111: 'Invoice ID',
  E112: 'Profile',
  E113: 'Save',
  E114: 'Ongoing',
  E115: 'Failed',
  E116: 'Expired',
  E117: 'ID',
}

export default English
